# Generated by Django 6.1.1 on 2026-09-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_address_lead_latitude_lead_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='longitude',
        ),
    ]
