# Generated by Django 5.2 on 2026-09-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_latitude_remove_lead_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
