# Generated by Django 6.1.1 on 2026-09-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_client_id_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
