# Generated by Django 6.1.1 on 2026-09-14 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0003_remove_lead_latitude_remove_lead_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_records', to='leads.lead')),
            ],
        ),
    ]
