# Generated by Django 6.1.1 on 2026-09-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_campaign_campaignlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignlead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('approved', 'Approved'), ('sent', 'Sent'), ('replied', 'Replied'), ('interested', 'Interested'), ('follow_up', 'Follow-up'), ('not_interested', 'Not Interested'), ('converted', 'Converted'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
